project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: CV/Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute: 
  freeze: auto



